const fs = require('fs');
const path = 'frontend/src/pages/company/ManageTrips.tsx';
let text = fs.readFileSync(path, 'utf8');
const startMarker = '      <div className="card p-3">\n        <h2 className="text-xl mb-3">Danh sA?ch chuy???n xe</h2>';
const endMarker = '\n\n\n      {cancelTripTarget && (';
const start = text.indexOf(startMarker);
const end = text.indexOf(endMarker);
if (start === -1 || end === -1 || end <= start) {
  throw new Error('Unable to locate trip list block');
}
const prefix = text.slice(0, start);
const suffix = text.slice(end);
const newLines = [
  '      <div className="card p-3">',
  '        <h2 className="text-xl mb-3">Danh sA?ch chuy???n xe</h2>',
  '        <div className="d-flex flex-wrap gap-3 mb-3">',
  '          <div className="flex-grow-1">',
  '            <label className="form-label">T???m kiA?m</label>',
  '            <input',
  '              type="text"',
  '              className="form-control"',
  '              placeholder="NhA?p tuy???n, ID, xe ho???c tA?i xA?"',
  '              value={searchTerm}',
  '              onChange={(event) => setSearchTerm(event.target.value)}',
  '            />',
  '          </div>',
  '          <div style={{ minWidth: \'200px\' }}>',
  '            <label className="form-label">Tr???ng thA?i</label>',
  '            <select',
  '              className="form-select"',
  '              value={statusFilter}',
  '              onChange={(event) => setStatusFilter(event.target.value as typeof statusFilter)}',
  '            >',
  '              <option value="ALL">T???t cA?</option>',
  '              <option value="SCHEDULED">??A? lA?n l??ch</option>',
  '              <option value="IN_PROGRESS">??ang chA?y</option>',
  '              <option value="COMPLETED">HoA?n thA?nh</option>',
  '              <option value="CANCELLED">??A? h???y</option>',
  '            </select>',
  '          </div>',
  '        </div>',
  '        <div className="table-responsive">',
  '          <table className="table">',
  '            <thead>',
  '              <tr>',
  '                <th>ID</th>',
  '                <th>Tuy???n</th>',
  '                <th>Kh??Yi hA?nh</th>',
  '                <th>?????n n??i</th>',
  '                <th>Xe</th>',
  '                <th>Tai xe</th>',
  '                <th>GiA?</th>',
  '                <th>Tr???ng thA?i</th>',
  '                <th>HA?nh ?`??Tng</th>',
  '              </tr>',
  '            </thead>',
  '            <tbody>',
  '              {paginatedTrips.map((trip) => (',
  '                <tr key={trip.id}>',
  '                  <td>{trip.id}</td>',
  '                  <td>{getRouteLabel(trip)}</td>',
  '                  <td>{new Date(trip.departureTime).toLocaleString(\'vi-VN\')}</td>',
  '                  <td>{new Date(trip.arrivalTime).toLocaleString(\'vi-VN\')}</td>',
  '                  <td>{trip.bus?.busNumber || \'Ch??a gA?n xe\'}</td>',
  '                  <td>{trip.driver?.user?.name || trip.driver?.user?.email || \'Chua phan tai xe\'}</td>',
  '                  <td>{Number(trip.basePrice || 0).toLocaleString(\'vi-VN\')} ?`</td>',
  '                  <td>',
  '                    <span className={`badge bg-${statusVariant(trip.status)}`}>
                      {toViStatus(trip.status)}
                    </span>',
  '                  </td>',
  '                  <td>',
  '                    <div className="d-flex gap-2">',
  '                      <button className="btn btn-outline-primary btn-sm" type="button" onClick={() => startEdit(trip)}>',
  '                        S??-a',
  '                      </button>',
  '                      <button className="btn btn-outline-warning btn-sm" type="button" onClick={() => handleOpenCancelTrip(trip)} disabled={trip.status === \'CANCELLED\'}>',
  '                        H??? chuy???n',
  '                      </button>',
  '                      <button className="btn btn-outline-danger btn-sm" type="button" onClick={() => handleDelete(trip.id)}>',
  '                        XA3a',
  '                      </button>',
  '                    </div>',
  '                  </td>',
  '                </tr>',
  '              ))}',
  '            </tbody>',
  '          </table>',
  '          {filteredTrips.length === 0 && (',
  '            <div className="text-center py-4 text-muted">',
  '              NhA? xe ch??a cA3 chuy???n nA?o. HA?y t???o chuy???n m??>i ?`??? b??_t ?`????u!',
  '            </div>',
  '          )}',
  '          {filteredTrips.length > 0 && (',
  '            <div className="d-flex justify-content-between align-items-center mt-3">',
  '              <span className="text-muted">',
  '                Trang {currentPage}/{totalPages} • {filteredTrips.length} chuy???n',
  '              </span>',
  '              <div className="btn-group">',
  '                <button',
  '                  type="button"',
  '                  className="btn btn-outline-secondary btn-sm"',
  '                  disabled={currentPage === 1}',
  '                  onClick={() => setCurrentPage((prev) => Math.max(1, prev - 1))}',
  '                >',
  '                  Tr??\'c',
  '                </button>',
  '                <button',
  '                  type="button"',
  '                  className="btn btn-outline-secondary btn-sm"',
  '                  disabled={currentPage >= totalPages}',
  '                  onClick={() => setCurrentPage((prev) => Math.min(totalPages, prev + 1))}',
  '                >',
  '                  Sau',
  '                </button>',
  '              </div>',
  '            </div>',
  '          )}',
  '        </div>',
  '      </div>',
  '',
  ''];
const newBlock = newLines.join('\n');
text = prefix + newBlock + suffix;
fs.writeFileSync(path, text, 'utf8');
